name: Validate JSON
on: [push]
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        run: jq . everest_story_catcher_specs.json
